gui:
  border: 'rounded'
  theme:
    lightTheme: false
    activeBorderColor:
      - "#fbf1c7"
      - bold
    inactiveBorderColor:
      - "#a89984"
    optionsTextColor:
      - "#665c54"
    selectedLineBgColor:
      - "#292e42"
      - bold
    selectedRangeBgColor:
      - "#89ddff"
  showBottomLine: false
